# Generated by Django 4.1 on 2022-08-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_address', models.TextField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phno', models.CharField(max_length=15)),
                ('c_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_description', models.TextField()),
                ('p_type', models.CharField(max_length=255)),
                ('p_price', models.IntegerField()),
                ('p_image', models.ImageField(upload_to='customer')),
                ('p_add_date', models.DateField(auto_now=True)),
                ('p_status', models.BooleanField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
    ]
